---
# This will be the name of your `app` on Digital Ocean
name: lobby-example-app-backend
services:
- name: lobby-example
  image:
    registry_type: DOCR
    # Replace the repository below with whatever you decided to name your repository
    repository: lobby-example
    tag: latest
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 8080
  routes:
  - path: "/"
  envs:
    - key: QUARKUS_MONDODB_CONNECTION_STRING
      scope: RUN_AND_BUILD_TIME
      type: SECRET
      value: {{ DB_URL }}
# region: nyc1